### ISSUE TITLE
Unresolved directive in <stdin> - include::../inc.adoc[]

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctor-firefox-addon#21]
To reproduce this issue, you need two files:

* `asciidoc/test.adoc`
* `inc.adoc`

The `test.adoc` file content is:

    content from `_src/docs/inc.adoc`.
    
    Hello *world*.

The `test.adoc` is a full asciidoctor article file (with title, header and so on) similar to the example you can find everywhere. Important is that this file contains:

    Some test.
    
    include::../inc.adoc[]
    
    This project does something.

When I try to preview the file in Firefox with the asciidoctor-firefox-addon extension, I get this output:

    Some test.
    
    Unresolved directive in <stdin> - include::../inc.adoc[] This project does something. We just haven’t decided what that is yet.

A google search pointed to this issue in asciidoctor.js: [#42: includes does not work correctly](https://github.com/asciidoctor/asciidoctor.js/issues/42)

**Comment by jmini** [comment]
The mentioned issue "includes does not work correctly" seems to be fixed with [asciidoctor/asciidoctor#1081](asciidoctor/asciidoctor#1081) (see this [comment](https://github.com/asciidoctor/asciidoctor.js/issues/42#issuecomment-63101571)).

This is why I have suggested to update the asciidoctor.js library with #22.

I think an update will fix this issue.

**Comment by Mogztter** [comment]
Resolved by #22

**Comment by jmini** [comment]
My test shows that this isssue is not solved.

    dir
    |   inc2.adoc
    |
    \---doc
        |   example-manual.adoc
        |   inc1.adoc
        |
        \---imgs
                sunset.jpg

The `example-manual.adoc` contains:

    = Example Manual
    This is a user manual for an example project.
    
        include::inc1.adoc[]
    
    include::inc1.adoc[]
    
        include::../inc2.adoc[]
    
    include::../inc2.adoc[]
    
    
    == Attributes
    
    .Built-in
    asciidoctor-version:: {asciidoctor-version}
    safe-mode-name:: {safe-mode-name}
    docdir:: {docdir}

And I still have the error:

![example-manual-preview](https://cloud.githubusercontent.com/assets/1222165/6075899/d1430c2e-addb-11e4-82c1-a25bae86a0cd.png)

Notice that the `asciidoctor-version` is correct (it was updated).

Can you reopen this?

**Comment by Mogztter** [comment]
I think I need to switch to safe-mode `safe`, not `server`

**Comment by Mogztter** [comment]
I think Firefox cannot get data from a different path from the one you are currently.
The XMLHttpRequest returns `NS_ERROR_DOM_BAD_URI`.

Ref:
http://ejohn.org/blog/tightened-local-file-security/
https://bugzilla.mozilla.org/show_bug.cgi?id=560488
https://bugzilla.mozilla.org/show_bug.cgi?id=465397
https://bugzilla.mozilla.org/show_bug.cgi?id=230606

**Comment by Mogztter** [comment]
Btw, thanks for your review on the Firefox AMO! :smile:

**Comment by mojavelinux** [comment]
> I think Firefox cannot get data from a different path from the one you are currently.

If I remember correctly from my tests, this is correct. I'm happy to be proven wrong.
